export const COLOR_EXTENSION_MAP: { [key: string]: string } = {
  pdf: "red",
  docx: "blue",
  xlsx: "yellow",
  pptx: "green",
  jpg: "cyan",
  png: "magenta",
  txt: "orange",
  gif: "pink",
  mp3: "purple",
  mp4: "brown",
  html: "teal",
  css: "lime",
  js: "indigo",
  php: "maroon",
  py: "olive",
  java: "navy",
  cpp: "coral",
  md: "peru",
  json: "khaki",
  xml: "orchid",
  exe: "steelblue",
  zip: "darkslategray",
  csv: "sienna",
  yaml: "dodgerblue",
  bmp: "violet",
  tiff: "gold",
  odt: "turquoise",
  ogg: "lavender",
  flv: "salmon",
  swf: "skyblue",
  asp: "tan",
  sh: "plum",
  bat: "darkkhaki",
  psd: "thistle",
  svg: "lightcoral",
  eps: "cadetblue",
  ttf: "hotpink",
  woff: "springgreen",
  wmv: "firebrick",
  avi: "royalblue",
  ogv: "darkorange",
  mov: "darkolivegreen",
  m4v: "mediumslateblue",
  mpeg: "saddlebrown",
  wav: "darkcyan",
  aiff: "crimson",
  ogm: "peru",
  mkv: "indianred",
  ico: "mediumvioletred",
  rtf: "midnightblue",
  htm: "mediumseagreen",
  srt: "cadetblue",
  ini: "chocolate",
};

// Types
type Extension =
  | "pdf"
  | "docx"
  | "xlsx"
  | "pptx"
  | "jpg"
  | "png"
  | "txt"
  | "gif"
  | "mp3"
  | "mp4"
  | "html"
  | "css"
  | "js"
  | "php"
  | "py"
  | "java"
  | "cpp"
  | "md"
  | "json"
  | "xml"
  | "exe"
  | "zip"
  | "csv"
  | "yaml"
  | "bmp"
  | "tiff"
  | "odt"
  | "ogg"
  | "flv"
  | "swf"
  | "asp"
  | "sh"
  //   | "bat"
  | "psd"
  | "svg"
  | "eps"
  | "ttf"
  | "woff"
  | "wmv"
  | "avi"
  | "ogv"
  | "mov"
  | "m4v"
  | "mpeg"
  | "wav"
  | "aiff"
  | "ogm"
  | "mkv"
  | "ico"
  | "rtf"
  | "htm"
  | "srt"
  | "ini";
type Color =
  | "red"
  | "blue"
  | "yellow"
  | "green"
  | "cyan"
  | "magenta"
  | "orange"
  | "pink"
  | "purple"
  | "brown"
  | "teal"
  | "lime"
  | "indigo"
  | "maroon"
  | "olive"
  | "navy"
  | "coral"
  | "peru"
  | "khaki"
  | "orchid"
  | "steelblue"
  | "darkslategray"
  | "sienna"
  | "dodgerblue"
  | "violet"
  | "gold"
  | "turquoise"
  | "lavender"
  | "salmon"
  | "skyblue"
  | "tan"
  | "plum"
  | "thistle"
  | "lightcoral"
  | "cadetblue"
  | "hotpink"
  | "springgreen"
  | "firebrick"
  | "royalblue"
  | "darkorange"
  | "darkolivegreen"
  | "mediumslateblue"
  | "saddlebrown"
  | "darkcyan"
  | "crimson"
  | "indianred"
  | "mediumvioletred"
  | "midnightblue"
  | "mediumseagreen"
  | "chocolate";

const COLOR_EXTENSION_MAP_TYPED: { [key in Extension]: Color } = {
  pdf: "red",
  docx: "blue",
  xlsx: "yellow",
  pptx: "green",
  jpg: "cyan",
  png: "magenta",
  txt: "orange",
  gif: "pink",
  mp3: "purple",
  mp4: "brown",
  html: "teal",
  css: "lime",
  js: "indigo",
  php: "maroon",
  py: "olive",
  java: "navy",
  cpp: "coral",
  md: "peru",
  json: "khaki",
  xml: "orchid",
  exe: "steelblue",
  zip: "darkslategray",
  csv: "sienna",
  yaml: "dodgerblue",
  bmp: "violet",
  tiff: "gold",
  odt: "turquoise",
  ogg: "lavender",
  flv: "salmon",
  swf: "skyblue",
  asp: "tan",
  sh: "plum",
  //   bat: "darkkhaki",
  psd: "thistle",
  svg: "lightcoral",
  eps: "cadetblue",
  ttf: "hotpink",
  woff: "springgreen",
  wmv: "firebrick",
  avi: "royalblue",
  ogv: "darkorange",
  mov: "darkolivegreen",
  m4v: "mediumslateblue",
  mpeg: "saddlebrown",
  wav: "darkcyan",
  aiff: "crimson",
  ogm: "peru",
  mkv: "indianred",
  ico: "mediumvioletred",
  rtf: "midnightblue",
  htm: "mediumseagreen",
  srt: "cadetblue",
  ini: "chocolate",
};
