import { NewFolder } from "../newFolder";
import FolderCard, { IFolder } from "../FolderCard";
import { ScrollArea } from "@/components/ui/scroll-area";
import Input from "@/components/ui/input";
import InputForm from "./InputForm";

const FolderGrid = () => {
  const folder = folders.map((folder: IFolder, index: number) => (
    <FolderCard key={index} folder={folder} />
  ));
  return (
    <div className="my-10 px-5">
      <InputForm />
      <div className="grid   md:grid-cols-2 lg:grid-cols-4 gap-3 mt-4">
        <div className="lg:flex hidden">
          <NewFolder />
        </div>
        {folder}
      </div>
    </div>
  );
};

export default FolderGrid;

const folders: IFolder[] = [
  {
    _id: 2,
    name: "documents",
    totalfiles: 500,
    size: 109,
    color: "blue",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
  {
    _id: 3,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "yellow",
  },
  {
    _id: 4,
    name: "images",
    totalfiles: 100,
    size: 109,
    color: "green",
  },
  {
    _id: 1,
    name: "pdf files",
    totalfiles: 20,
    size: 109,
    color: "red",
  },
  {
    _id: 5,
    name: "personal details",
    totalfiles: 200,
    size: 109,
    color: "green",
  },
];
